### PR TITLE
Fix tap repetition when `homebrew-` is present on the name

### LINKED ISSUE #65: Tap adds taps that are already present
There's an edge case when a tap contains `homebrew-` on the name that the module will re-add that tap even though is already present. This happens because when brew taps a tap with a name like that, the `homebrew-` is removed from the name.

To make it easier to understand here an example:
`brew tap improbable-io/homebrew-versions`
Will result in...
```
$ brew tap
improbable-io/versions
```
Therefore when the module checks if a tap is already present by comparing `brew tap` with the name of the tap we want to add, it will never match.

There are two possible fixes:
1. Remove `homebrew-` from any tap name on the puppet manifest.
2. Make sure the module can support this edge case by comparing against the name and the name minus the `homebrew-` part.

I think the sane way to proceed is the second one. Will submit a PR.

### PR DESCRIPTION
**Pull request by jordigg**
Fix tap repetition when `homebrew-` is present on the name, should fix #65

### CODE REVIEW

File: lib/puppet/provider/package/tap.rb [hunk 1]
```diff
@@ -37,7 +37,7 @@ def query
       output = execute([command(:brew), :tap])
       output.each_line do |line|
         line.chomp!
-        return { :name => line, :ensure => 'present', :provider => 'tap' } if line.downcase == name
+        return { :name => line, :ensure => 'present', :provider => 'tap' }  if line.downcase == name || line.downcase == name.gsub('homebrew-', '')
```
Comment (TheKevJames) [inline lib/puppet/provider/package/tap.rb]: Could you just do this as `[name, name.gsub('homebrew-', '')].include? line.downcase`? I think that'll be a bit easier to parse, in case we ever have to add more cases.

**Comment by jordigg** [comment]
Makes sense, updated PR
